[target.'cfg(any(target_arch = "x86", target_arch = "x86_64"))']
# Use native CPU optimization for maximum performance
rustflags = [
    "-C",
    "target-cpu=native",
    "-C",
    "target-feature=+sse2,+sse3,+sse4.1,+ssse3,+avx,+avx2",
]
# rustflags = ["-C", "target-feature=+sse2,+sse3,+sse4.1,+ssse3,+avx,+avx2,+avx512f,+avx512bw,+avx512vl"]

[target.'cfg(target_arch = "aarch64")']
rustflags = ["-C", "target-cpu=native", "-C", "target-feature=+neon"]
#rustflags = ["-C", "target-feature=+neon,+sve,+sve2"]
